name:Login

on:
  schedule:
    - cron: '0 0 */3 * *'  # 每三天執行一次
  workflow_dispatch:  # 允許手動觸發

jobs:
  auto-login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup jq
        run: sudo apt-get install -y jq  # 安裝 jq 用於解析 JSON

      - name: Auto Login
        env:
          CREDENTIALS: ${{ secrets.WEBSITE }}
        run: |
          # 定義網站列表
          SITES=("infini-cloud.net")

          # 遍歷網站並進行自動登錄
          for SITE in "${SITES[@]}"; do
            # 使用 jq 解析 JSON，根據網站提取相應的帳號和密碼
            USERNAME=$(echo "$CREDENTIALS" | jq -r --arg site "$SITE" '.[] | select(.ip == $site) | .username')
            PASSWORD=$(echo "$CREDENTIALS" | jq -r --arg site "$SITE" '.[] | select(.ip == $site) | .password')
            
            if [ -n "$USERNAME" ] && [ -n "$PASSWORD" ]; then
              echo "Logging into $SITE with username $USERNAME"
              # 執行登入請求
              curl -X POST -d "username=$USERNAME&password=$PASSWORD" "https://$SITE/login"
            else
              echo "No credentials found for $SITE"
            fi
          done
